### ISSUE TITLE
Q mal Lo hacen

### ISSUE THREAD

**Issue by mikefernandz** [k4s1pro/torghast-project-5.4.8#1]
Simplemente Q mal lo haces si te incomodava algo existian otras maneras de hacerlo 
 
Acabas de darle un buen golpe a todos los desarrolladores q se esforsaron para llegar ala calidad de ese codigo ,ojala no se revele tu verdadera identidad men  y q nunca tu gran codigo de cataclismo nunca se filtre para q sientas lo q estan sintiendo esos desarrolladores de dicho proyecto  (Saludos)

**Comment by k4s1pro** [comment]
Mira nene, lo primero no amenaces con que si supieran mi identidad que? me van a matar o algo por publicar un código de un server que murió hace tiempo, si hace tiempo listo que no te enteras de nada, este código pertenecía a insengar.ru lo que después lo compraron y lo han echo suyo no significa que sea de ellos, aparte todo esto pertenece a blizzard da igual que tu hagas el código el juego es suyo así que déjate de tontearías que yo al menos lo publico para que todo el mundo pueda disfrutar de algo que no tendría que ser privado, como tantos códigos que hay, si lo e publicado es por que me da la gana y no quiero que sigan sacando dinero por este código por que lo están aprovechando y bien así que suerte chaval.

**Comment by mikefernandz** [comment]
tonterias, bueno lo echo echo esta q les valla bien saludos

**Comment by mikefernandz** [comment]
Gracias a eso veras que empezará la fiebre de pandaria . no era amenaza al
final yo no soy nadie y si quieres borra el comentario del github pero
bueno muchas personas viven de su trabajo y acabas de malgastarle años a
unos cuantos y se va a recrudecer más la venta de ese codigo ,q van hacer
le cambian el copyright  y lo venden como de otro proyecto no es la primera
ves q pasa mira lo q paso con uwow.
