### ISSUE TITLE
Unknown compiler version

### ISSUE THREAD

**Issue by Nexon99** [k4s1pro/torghast-project-5.4.8#12]
I have successfully compiled the source. Apparently without error, but one thing intrigues me. 
This : `Unknown compiler version - please run the configure tests and report the results`

I find it strange that the compilation is successful while I have "errors" like that. 🤔

**Comment by Ramys** [comment]
> I have successfully compiled the source. Apparently without error, but one thing intrigues me. This : `Unknown compiler version - please run the configure tests and report the results`
> 
> I find it strange that the compilation is successful while I have "errors" like that. 🤔

Core in development, fixes little by little.

Close This.

**Comment by Nexon99** [comment]
Okay, and import "DBFULLWORLD" not working. I tried with 2 different programs.
