### ISSUE TITLE
not anera 

### ISSUE THREAD

**Issue by JadeCore** [k4s1pro/torghast-project-5.4.8#23]
.npc add 78461

**Comment by Ramys** [comment]
???

**Comment by Ramys** [comment]
I believe they are talking about the arena npcs in pandaria, they are not active in the bases..
Base Alliance and Horde.
@k4s1pro

**Comment by JadeCore** [comment]
there is no vendor who sells things arena

**Comment by JadeCore** [comment]
otsutsvuet   vendor  https://ru.wowhead.com/npc=78461/%D1%88%D0%BE%D0%BD%D0%BD-%D1%81%D1%83

**Comment by Ramys** [comment]
https://github.com/alexkulya/pandaria_5.4.8/commit/214fe8933359571c039e34c921da144745772c70

https://github.com/alexkulya/pandaria_5.4.8/commit/214fe8933359571c039e34c921da144745772c70
Try this.

**Comment by Ramys** [comment]
Sorted out?

**Comment by k4s1pro** [comment]
it's very easy, if i remember correctly you have to put yourself in gm mode and they are in other phases, you change the phase and that's it. i put it this way because it was progressive.

**Comment by JadeCore** [comment]
vendor is not added in any way

**Comment by Ramys** [comment]
Add manualy..
