### ISSUE TITLE
Error compilation windows

### ISSUE THREAD

**Issue by Ramys** [k4s1pro/torghast-project-5.4.8#3]
torghast-project-5.4.8 \ src \ server \ scripts \ Spells \ spell_warrior.cpp (339): warning C4715: 'spell_warr_unbridled_wrath :: spell_warr_unbridled_wrath_AuraScript :: checkProc': all control paths a value
torghast-project-5.4.8\src\server\scripts\Custom\protected_zone.cpp(25,1): warning C4060: switch statement contains no 'case' or 'default' label

win 10 x64
Visual Studio 19

@k4s1pro

**Comment by k4s1pro** [comment]
They are warnings, I would have to let compile the solution anyway, anyway I compile it with visual 15 (2017)

**Comment by Ramys** [comment]
leave a repack of auth and world for download

**Comment by k4s1pro** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-general-releases/959069-repack-torghast-project-mist-of-pandaria-5-4-8-a.html

**Comment by Ramys** [comment]
Thk.

**Comment by k4s1pro** [comment]
Severity Code Description Project File Line Suppression State
Error C2059 syntax error: '}' game Core-5.4.8\src\server\game\Services\ServiceMgr.cpp 276
