### ISSUE TITLE
Boost problem

### ISSUE THREAD

**Issue by Nexon99** [k4s1pro/torghast-project-5.4.8#6]
I can't find this version : **Win64OpenSSL-1_0_2d**. 

So `CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/macros/FindOpenSSL.cmake:190 (find_package_handle_standard_args)
  CMakeLists.txt:75 (find_package)`

**Comment by Nexon99** [comment]
**Fixed** : x64 plateform selected.

But problem with boost 

```
Environment variable Boost_ROOT is set to:

    C:/local/boost_1_63_0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

I've the boost_1_63_0-msvc-14.0-64 version.

**Comment by DarkAngelDE** [comment]
have you set BOOST_ROOT ?

**Comment by Nexon99** [comment]
Yes ! https://www.zupimages.net/up/21/49/xw6p.png

**Comment by Nexon99** [comment]
No one ?

**Comment by k4s1pro** [comment]
hi https://zupimages.net/viewer.php?id=21/50/twyw.jpg remove the top root and put it as in the picture.

**Comment by Nexon99** [comment]
Same error https://www.zupimages.net/up/21/50/m4x6.png 😒🤔

**Comment by Ramys** [comment]
> Same error (after restart) https://www.zupimages.net/up/21/50/m4x6.png 😒🤔
Hello man, install these programs, it works normally for me.
https://drive.google.com/file/d/1WLJxNEhmf7SiC549X4mzI9u_4-33nOw7/view?usp=sharing

**Comment by Nexon99** [comment]
Thanks ! Now working 😁👌

**Comment by Ramys** [comment]
=)
